openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8082/order-apis
  description: Generated server url
paths:
  /order-apis/order:
    get:
      tags:
      - order-controller
      operationId: getAllOrder
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
    post:
      tags:
      - order-controller
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Order"
  /order-apis:
    get:
      tags:
      - order-controller
      operationId: test
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /order-apis/order/{orderId}:
    get:
      tags:
      - order-controller
      operationId: getOrderByOrderId
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Order"
    delete:
      tags:
      - order-controller
      operationId: deleteOrderByOrderId
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        orderId:
          type: string
        productId:
          type: string
          minLength: 1
        userId:
          type: string
          minLength: 1
        qty:
          type: integer
          format: int64
        totalPrice:
          type: number
          format: double
      required:
      - productId
      - userId
