openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8081/account-apis
  description: Generated server url
paths:
  /account-apis/account:
    get:
      tags:
      - account-controller
      operationId: getAccounts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
    post:
      tags:
      - account-controller
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /account-apis/account/{userId}:
    get:
      tags:
      - account-controller
      operationId: getAccount
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - account-controller
      operationId: getUserData
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    patch:
      tags:
      - account-controller
      operationId: getUserData_1
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Account"
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
      required:
      - email
      - name
      - password
